export { default as Navbar } from "./navbar/navbar" 
export { default as Footer } from "./footer/footer" 
export { default as Hero } from "./hero/hero" 
export { default as TrendMovies } from "./trendmovies/trendmovies" 
export { default as SingleMovie } from "./singlemovie/singlemovie"  
export { default as PopularMovies } from "./popularmovies/popularmovies" 
export { default as Credits } from "./credits/credits" 
export { default as RecommendMovies } from "./recommed/recommed" 
export { default as Officials } from "./official/official" 
export { default as Spinner } from "./Spinner" 

